---
#  ███╗   ██╗███████╗██████╗ ████████╗██╗   ██╗███╗   ██╗███████╗
#  ████╗  ██║██╔════╝██╔══██╗╚══██╔══╝██║   ██║████╗  ██║██╔════╝
#  ██╔██╗ ██║█████╗  ██████╔╝   ██║   ██║   ██║██╔██╗ ██║█████╗
#  ██║╚██╗██║██╔══╝  ██╔═══╝    ██║   ██║   ██║██║╚██╗██║██╔══╝
#  ██║ ╚████║███████╗██║        ██║   ╚██████╔╝██║ ╚████║███████╗
#  ╚═╝  ╚═══╝╚══════╝╚═╝        ╚═╝    ╚═════╝ ╚═╝  ╚═══╝╚══════╝
#                             V1.0

# Language configuration
lang:
  prefix: '&8[&b&lNeptune&8] &r&7'
  no-permission: '&cNo permission.'
  base-message-color: '&b'
  flag-format: '%prefix%&c%player% &7has failed &c%check% &8<&c%checktype%&8> &8[&7VL&8:&c %vl%&8]'
  experimental-annotation: '&f*'
  broadcast-message: '%newline%%prefix%%player% &7was banned for &fCheating&7.%newline% '

# Check configuration
checks:
  punish-command: 'kick %player% %prefix%Cheating'
  broadcast-punishments: true
  detections:
    speed:
      a:
        enabled: true
        punishable: true
        max-vl: 10
      b:
        enabled: true
        punishable: true
        max-vl: 10
      c:
        enabled: true
        punishable: true
        max-vl: 10
      d:
        enabled: true
        punishable: true
        max-vl: 10
      e:
        enabled: true
        punishable: true
        max-vl: 10
    fly:
      a:
        enabled: true
        punishable: true
        max-vl: 10
      b:
        enabled: true
        punishable: false
        max-vl: 10
      c:
        enabled: true
        punishable: true
        max-vl: 10
      d:
        enabled: true
        punishable: true
        max-vl: 10
    motion:
      a:
        enabled: true
        punishable: true
        max-vl: 10
      b:
        enabled: true
        punishable: true
        max-vl: 10
      c:
        enabled: true
        punishable: true
        max-vl: 10
    fastladder:
      a:
        enabled: true
        punishable: true
        max-vl: 10
    noslowdown:
      a:
        enabled: true
        punishable: true
        max-vl: 10
    phase:
      a:
        enabled: true
        punishable: false
        max-vl: 10
    nofall:
      a:
        enabled: true
        punishable: true
        max-vl: 10
    badpackets:
      a:
        enabled: true
        punishable: true
        max-vl: 10
      b:
        enabled: true
        punishable: false
        max-vl: 10
      c:
        enabled: true
        punishable: true
        max-vl: 10
    horion:
      a:
        enabled: true
        punishable: true
        max-vl: 1
...